### ISSUE TITLE
"you need to update your app" issue

### ISSUE THREAD

**Issue by LaffX** [RojanGamingYT/Discord-Username-Sniper#10]
"you need to update your app" issue

**Comment by RojanGamingYT** [comment]
yes, I am quite aware of this error, After Fixing some codes from the previous release this error's solution is yet undiscovered and I have tried fixing the "You need to update your app to perform this action." but it isn't working, the error is passed due to an unknown reason which I am trying to find out.

**Comment by RojanGamingYT** [comment]
The New Version is **OUT** , This Issue has been Solved in that Version
